---
githubConfigUrl: https://github.com/CASL0/actions-runner-controller-helmfile
runnerScaleSetName: my-arc-runners
maxRunners: 5
minRunners: 0
template:
  spec:
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
githubConfigSecret: arc-runners-secret
controllerServiceAccount:
  namespace: arc-system
  name: arc-gha-rs-controller
listenerTemplate:
  spec:
    containers:
      - name: listener
        securityContext:
          runAsUser: 1000
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"
